# Generated by Django 5.1 on 2024-08-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edulearnapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
